---
title: "FinalProject"
output:
  pdf_document: default
  html_document: default
date: "2023-11-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data <- read.csv('dataset.csv')
```

```{r}

library(tidyverse)

data <- data %>%
  distinct(track_id, .keep_all = TRUE)

```
```{r}
data <- data %>%
  group_by(artists, track_name) %>%
  filter(row_number() == 1) %>%
  ungroup()

```

```{r}
mod<-lm(popularity~danceability + key + energy + loudness + mode+speechiness+acousticness + instrumentalness+liveness+valence + tempo +duration_ms +time_signature,data)
```

```{r}
summary(mod)
```



```{r}
head(data)
```

```{r}
set.seed(2202)
data <- data[sample(nrow(data), 2000, replace = FALSE),]
```


```{r}
library(stringdist)
library(dplyr)
set.seed(2202)

get_similarity_factors <- function(song_name, data) {
  target_row <- data[data$track_name == song_name, ]
  
  if (nrow(target_row) == 0) {
    cat('This song is either not so popular or you have entered an invalid name.\nSome songs you may like:\n')
    
    sample_indices <- sample(seq_len(nrow(data)), 5)
    sample_songs <- data$track_name[sample_indices]
    
    cat(sample_songs, '\n')
    return(NULL)
  }
  
  features_to_compare <- c( "danceability", "key", "energy", "loudness", 
                            "mode", "speechiness", "acousticness", 
                            "instrumentalness", "liveness", "valence", 
                            "tempo", "time_signature")
  
  target_features <- as.matrix(target_row[, features_to_compare])
  
  if (!all(sapply(target_features, is.numeric))) {
    stop("Non-numeric values found in the target features.")
  }
  
  data %>%
    rowwise() %>%
    mutate(
      feature_similarity = proxy::dist(target_features, 
                                       as.matrix(select(., all_of(features_to_compare))), 
                                       method = "cosine")[1]
    ) %>%
    ungroup() %>%
    arrange(desc(feature_similarity), desc(popularity)) %>%
    select(track_name, artists)
}

recommend_songs <- function(song_name, data) {
  get_similarity_factors(song_name, data) %>% slice(3:8)
}

recommend_songs('When We Were Young', data = data)

```



```{r}
set.seed(2202)
# a 50 by 2 matrix from a standard normal distribution
x <- as.matrix(data[, c("popularity", "time_signature")])
# the first 25 data points have a mean shift relative to the next 25 observations
x[1:25, 1] <- x[1:25, 1] + 3
x[1:25, 2] <- x[1:25, 2] - 4

# perform k-means clustering with k=2
# nstart is the number of random initialization
# the function will output the result with minimum within-cluster variation
km.out <- kmeans(x, 2, nstart = 25)

# output the cluster assignment
km.out$cluster
km.out$cluster[1:25]
km.out$cluster[26:50]

plot(x, col = km.out$cluster,
     main = "K-Means Clustering Results with K = 2",
     xlab = "x1", ylab = "x2", pch = 20, cex = 2)

# the smallest within cluster variation among 25 random initiations k=2
km.out <- kmeans(x, 2, nstart = 25)
km.out$tot.withinss

# the smallest within cluster variation among 25 random initiations k=3
km.out <- kmeans(x, 3, nstart = 25)
km.out$tot.withinss

# plot clustering result
plot(x, col = km.out$cluster, main = "K-Means Clustering Results with K = 3",
     xlab = "", ylab = "", pch = 20, cex = 2)

# find best K
within.var <- c()
for(k in 2:20){
  km.out <- kmeans(scale(x), k, nstart = 25)
  within.var[k-1] <- km.out$tot.withinss
}
plot(within.var, type = 'l')
```
```{r}
set.seed(2202)
# a 50 by 2 matrix from a standard normal distribution
x <- as.matrix(data[, c("popularity", "duration_ms")])
# the first 25 data points have a mean shift relative to the next 25 observations
x[1:25, 1] <- x[1:25, 1] + 3
x[1:25, 2] <- x[1:25, 2] - 4

# perform k-means clustering with k=2
# nstart is the number of random initialization
# the function will output the result with minimum within-cluster variation
km.out <- kmeans(x, 2, nstart = 25)

# output the cluster assignment
km.out$cluster
km.out$cluster[1:25]
km.out$cluster[26:50]

plot(x, col = km.out$cluster,
     main = "K-Means Clustering Results with K = 2",
     xlab = "x1", ylab = "x2", pch = 20, cex = 2)

# the smallest within cluster variation among 25 random initiations k=2
km.out <- kmeans(x, 2, nstart = 25)
km.out$tot.withinss

# the smallest within cluster variation among 25 random initiations k=3
km.out <- kmeans(x, 3, nstart = 25)
km.out$tot.withinss

# plot clustering result
plot(x, col = km.out$cluster, main = "K-Means Clustering Results with K = 3",
     xlab = "", ylab = "", pch = 20, cex = 2)

# find best K
within.var <- c()
for(k in 2:20){
  km.out <- kmeans(scale(x), k, nstart = 25)
  within.var[k-1] <- km.out$tot.withinss
}
plot(within.var, type = 'l')
```

```{r}
set.seed(2202)
# a 50 by 2 matrix from a standard normal distribution
x <- as.matrix(data[, c("tempo", "popularity")])
# the first 25 data points have a mean shift relative to the next 25 observations
x[1:25, 1] <- x[1:25, 1] + 2
x[1:25, 2] <- x[1:25, 2] + 1

# perform k-means clustering with k=2
# nstart is the number of random initialization
# the function will output the result with minimum within-cluster variation
km.out <- kmeans(x, 2, nstart = 25)

# output the cluster assignment
km.out$cluster
km.out$cluster[1:25]
km.out$cluster[26:50]


# Display the smallest within-cluster variation among 25 random initiations k=3
km.out <- kmeans(x, 3, nstart = 25)
km.out$tot.withinss

# Plot clustering result with customized colors
plot(x, col = c("#246A73", "#38023B","#B2EDC5")[km.out$cluster],
     main = "K-Means Clustering Results with K = 3",
     xlab = "Tempo", ylab = "Popularity", pch = 20, cex = 2)

# Find the best K
within.var <- c()
for(k in 2:20) {
  km.out <- kmeans(scale(x), k, nstart = 25)
  within.var[k - 1] <- km.out$tot.withinss
}

# Plot within-cluster variation for different K values
plot(within.var, type = 'l', xlab = "Number of Clusters (K)", ylab = "Within-Cluster Variation", main = "Within-Cluster Variation vs. K")

```

```{r}
set.seed(2202)
# a 50 by 2 matrix from a standard normal distribution
x <- as.matrix(data[, c("duration_ms", "popularity")])
# the first 25 data points have a mean shift relative to the next 25 observations
x[1:25, 1] <- x[1:25, 1] - 2
x[1:25, 2] <- x[1:25, 2] -3

# perform k-means clustering with k=2
# nstart is the number of random initialization
# the function will output the result with minimum within-cluster variation
km.out <- kmeans(x, 2, nstart = 25)

# output the cluster assignment
km.out$cluster
km.out$cluster[1:25]
km.out$cluster[26:50]


# Display the smallest within-cluster variation among 25 random initiations k=3
km.out <- kmeans(x, 3, nstart = 25)
km.out$tot.withinss

# Plot clustering result with customized colors
plot(x, col = c("#246A73", "#38023B","#B2EDC5")[km.out$cluster],
     main = "K-Means Clustering Results with K = 3",
     xlab = "duration_ms", ylab = "Popularity", pch = 20, cex = 2)

# Find the best K
within.var <- c()
for(k in 2:20) {
  km.out <- kmeans(scale(x), k, nstart = 25)
  within.var[k - 1] <- km.out$tot.withinss
}

# Plot within-cluster variation for different K values
plot(within.var, type = 'l', xlab = "Number of Clusters (K)", ylab = "Within-Cluster Variation", main = "Within-Cluster Variation vs. K")

```

```{r}
set.seed(2202)
# a 50 by 2 matrix from a standard normal distribution
x <- as.matrix(data[, c("valence", "popularity")])
# the first 25 data points have a mean shift relative to the next 25 observations
x[1:25, 1] <- x[1:25, 1] + 2
x[1:25, 2] <- x[1:25, 2] + 1

# perform k-means clustering with k=2
# nstart is the number of random initialization
# the function will output the result with minimum within-cluster variation
km.out <- kmeans(x, 2, nstart = 25)

# output the cluster assignment
km.out$cluster
km.out$cluster[1:25]
km.out$cluster[26:50]


# Display the smallest within-cluster variation among 25 random initiations k=3
km.out <- kmeans(x, 3, nstart = 25)
km.out$tot.withinss

# Plot clustering result with customized colors
plot(x, col = c("#246A73", "#38023B","#B2EDC5")[km.out$cluster],
     main = "K-Means Clustering Results with K = 3",
     xlab = "valence", ylab = "Popularity", pch = 20, cex = 2)

# Find the best K
within.var <- c()
for(k in 2:20) {
  km.out <- kmeans(scale(x), k, nstart = 25)
  within.var[k - 1] <- km.out$tot.withinss
}

# Plot within-cluster variation for different K values
plot(within.var, type = 'l', xlab = "Number of Clusters (K)", ylab = "Within-Cluster Variation", main = "Within-Cluster Variation vs. K")

```
```{r}
set.seed(2202)
# a 50 by 2 matrix from a standard normal distribution
x <- as.matrix(data[, c("energy", "popularity")])
# the first 25 data points have a mean shift relative to the next 25 observations
x[1:25, 1] <- x[1:25, 1] + 2
x[1:25, 2] <- x[1:25, 2] - 1

# perform k-means clustering with k=2
# nstart is the number of random initialization
# the function will output the result with minimum within-cluster variation
km.out <- kmeans(x, 2, nstart = 25)

# output the cluster assignment
km.out$cluster
km.out$cluster[1:25]
km.out$cluster[26:50]


# Display the smallest within-cluster variation among 25 random initiations k=3
km.out <- kmeans(x, 3, nstart = 25)
km.out$tot.withinss

# Plot clustering result with customized colors
plot(x, col = c("#246A73", "#38023B","#B2EDC5")[km.out$cluster],
     main = "K-Means Clustering Results with K = 3",
     xlab = "energy", ylab = "Popularity", pch = 20, cex = 2)

# Find the best K
within.var <- c()
for(k in 2:20) {
  km.out <- kmeans(scale(x), k, nstart = 25)
  within.var[k - 1] <- km.out$tot.withinss
}

# Plot within-cluster variation for different K values
plot(within.var, type = 'l', xlab = "Number of Clusters (K)", ylab = "Within-Cluster Variation", main = "Within-Cluster Variation vs. K")

```

```{r}
set.seed(2202)
# Generate data with distinct clusters
selected_features <- data[, c("duration_ms", "energy", "loudness", "tempo")]

# Shift the mean for the first 25 observations
selected_features[1:25, "duration_ms"] <- selected_features[1:25, "duration_ms"] + 3
selected_features[1:25, "energy"] <- selected_features[1:25, "energy"] - 4
selected_features[1:25, "energy"] <- selected_features[1:25, "energy"] - 4

# Perform k-means clustering with k=3
k <- 3
km.out <- kmeans(scale(selected_features), k, nstart = 25)

# Add cluster assignment to the original data
data$cluster <- km.out$cluster

# Check summary and table
summary(data$cluster)
table(data$cluster, data$popularity)

# Plot clustering result
pairs(scale(selected_features), col = km.out$cluster, pch = 20, main = paste("K-Means Clustering Results with K =", k))

# Display cluster centers and within-cluster variation
km.out$centers
km.out$tot.withinss

```

```{r}
set.seed(2202)
selected_features <- data[, c("duration_ms", "danceability", "energy", "loudness", "valence", "tempo")]

# Standardize or normalize features
scaled_features <- scale(selected_features)

# Adjust the value of k based on your analysis
k <- 2
km.out <- kmeans(scaled_features, k, nstart = 25)

# Check the summary and table
summary(data$cluster)
table(data$cluster, data$popularity)

# Use adjusted colors for plotting
pairs(scaled_features, col = c("#246A73", "#38023B")[km.out$cluster], pch = 20)

# Display cluster centers and within-cluster variation
km.out$centers
km.out$tot.withinss

```

